name: Build

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: 🔨 Build
    runs-on: macos-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Set up gradle version
        run: ./gradlew wrapper --gradle-version=8.0.2

      - name: Build app with Gradle
        run: ./gradlew assemble --stacktrace --no-daemon

  unit-tests:
    name: 🧪 Run Tests
    runs-on: macos-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Set up gradle version
        run: ./gradlew wrapper --gradle-version=8.0.2

      - name: Execute unit tests
        run: ./gradlew test --stacktrace
        continue-on-error: true