name: Build

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Set up gradle version
        run: ./gradlew wrapper --gradle-version=8.0-rc-1

      - name: Build app with Gradle
        run: ./gradlew :shared:build --stacktrace --no-daemon

  unit-tests:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Set up gradle version
        run: ./gradlew wrapper --gradle-version=8.0-rc-1

      - name: Execute unit tests
        run: ./gradlew test

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}